# Generated by Django 5.2.4 on 2025-08-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
    ]
